---
kind: pipeline
name: update repository

steps:
  - name: test
    image: python:3.6
    commands:
      - echo test

trigger:
  cron:
    - update-repository-every-hour

---
kind: pipeline
name: openssl-1.1.1a

steps:
    # Start the sut (system under test)
  - name: sut
    image: tlsprint/openssl:1.1.1a
    detach: true

    # Start the connector with a delay of 5 seconds, so the sut has time to
    # initialize.
  - name: connector
    image: tlsprint/tlsattackerconnector
    pull: always
    detach: true
    commands:
      - connector
        --targetHost sut
        --protocolVersion TLS12
        --cipherSuite "TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA"
        --startupDelay 5000

    # Perform the learning
  - name: learner
    image: tlsprint/statelearner
    pull: always
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - sleep 10
      - statelearner
      - "cp output_server/learnedModel.dot /tmp/cache/learnedModel.dot"

  - name: commit
    image: python:3.6
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - pip install -r requirements.txt
      - python commit_model.py
        --implementation openssl
        --version 1.1.1a
        --tls-version TLS12
        --model /tmp/cache/learnedModel.dot
        --verbose
    environment:
      GITLAB_TLSPRINT_API_KEY:
        from_secret: GITLAB_TLSPRINT_API_KEY

volumes:
  - name: cache
    temp: {}

trigger:
  event:
    exclude:
      - "*"
  cron:
    - learn-new-models-every-day
