---
kind: pipeline
name: openssl-1.1.1

steps:
    # Start the sut (system under test)
  - name: sut
    image: tlsprint/openssl:1.1.1
    detach: true

    # Start the connector with a delay of 5 seconds, so the sut has time to
    # initialize.
  - name: connector
    image: tlsprint/tlsattackerconnector
    pull: always
    commands:
      - connector
        --targetHost sut
        --protocolVersion TLS12
        --cipherSuite "TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA"
        --startupDelay 5000

    # Perform the learning
  - name: learner
    image: tlsprint/statelearner
    pull: always
    commands:
      - statelearner
