image: python:3.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip install -r requirements.txt


update_repo:
  script:
    - python update_repository.py --verbose --commit
  only:
    - schedules
